version: '3.8'

x-django-base: &django-base
  build: .
  volumes:
    - .:/code
  env_file:
    - .env
  environment:
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    DJANGO_DEBUG: ${DJANGO_DEBUG}
    DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_PORT: ${POSTGRES_PORT}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PORT: ${REDIS_PORT}
    RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    RABBITMQ_HOST: ${RABBITMQ_HOST}
    RABBITMQ_PORT: ${RABBITMQ_PORT}
  depends_on:
    - db
    - redis
    - rabbitmq

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  celery:
    <<: *django-base
    command: celery -A rabbitmqtest worker --loglevel=info

volumes:
  postgres_data: